apiVersion: apps/v1
kind: Deployment
metadata:
  name: training-cicd
  labels:
    app: training-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: training-cicd
  template:
    metadata:
      labels:
        app: training-cicd
    spec:
      containers:
        - name: training-cicd
          image: fahmiwah/training-cicd:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGHOST
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: host
            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: user
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: password
            - name: PGDATABASE
              value: users_dev
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 20
